org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.configureondemand=false
org.gradle.parallel=true
org.gradle.caching=false

kotlin.code.style=official

kotlin.mpp.androidSourceSetLayoutVersion=2

android.useAndroidX=true

#Enable commonizer
kotlin.native.ignoreDisabledTargets=true

#iOS
xcodeproj=ios-app-swiftui/ios-app-swiftui.xcworkspace

kotlin.native.cacheKind.iosSimulatorArm64=none

