org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.configureondemand=false
org.gradle.parallel=true
org.gradle.caching=true

kotlin.code.style=official

kotlin.mpp.androidSourceSetLayoutVersion=2

android.useAndroidX=true

#Enable commonizer
kotlin.native.ignoreDisabledTargets=true

#iOS
xcodeproj=ios-app/ios-app.xcworkspace