object Plugins {
    const val androidApplication = "com.android.application"
    const val androidConvention = "android-convention"
    const val kotlinMultiplatformConvention = "kotlin-multiplatform-convention"
    const val kotlinKapt = "kotlin-kapt"
    const val kotlinAndroid = "kotlin-android"
    const val mobileMultiplatform = "dev.icerock.mobile.multiplatform"
    const val iosFramework = "dev.icerock.mobile.multiplatform.ios-framework"
    const val signing = "signing"
    const val swiftPackage = "com.chromaticnoise.multiplatform-swiftpackage"
    const val kSwift = "dev.icerock.moko.kswift"
    const val kotlinSerialization = "kotlinx-serialization"
    const val mavenPublishConfig = "maven-publish-config"
    const val cocoaPods = "org.jetbrains.kotlin.native.cocoapods"
}